import SharkeyEntity from './entity.js'

namespace SharkeyNotificationType {
  export const Follow: SharkeyEntity.NotificationType = 'follow'
  export const Mention: SharkeyEntity.NotificationType = 'mention'
  export const Reply: SharkeyEntity.NotificationType = 'reply'
  export const Renote: SharkeyEntity.NotificationType = 'renote'
  export const Quote: SharkeyEntity.NotificationType = 'quote'
  export const Reaction: SharkeyEntity.NotificationType = 'reaction'
  export const PollEnded: SharkeyEntity.NotificationType = 'pollEnded'
  export const ReceiveFollowRequest: SharkeyEntity.NotificationType = 'receiveFollowRequest'
  export const FollowRequestAccepted: SharkeyEntity.NotificationType = 'followRequestAccepted'
  export const Note: SharkeyEntity.NotificationType = 'note'
  export const RoleAssigned: SharkeyEntity.NotificationType = 'roleAssigned'
  export const ChatRoomInvitationReceived: SharkeyEntity.NotificationType = 'chatRoomInvitationReceived'
  export const AchievementEarned: SharkeyEntity.NotificationType = 'achievementEarned'
  export const ExportCompleted: SharkeyEntity.NotificationType = 'exportCompleted'
  export const ImportCompleted: SharkeyEntity.NotificationType = 'importCompleted'
  export const Login: SharkeyEntity.NotificationType = 'login'
  export const CreateToken: SharkeyEntity.NotificationType = 'createToken'
  export const App: SharkeyEntity.NotificationType = 'app'
  export const Test: SharkeyEntity.NotificationType = 'test'
  export const Edited: SharkeyEntity.NotificationType = 'edited'
  export const ScheduledNoteFailed: SharkeyEntity.NotificationType = 'scheduledNoteFailed'
  export const ScheduledNotePosted: SharkeyEntity.NotificationType = 'scheduledNotePosted'
  export const SharedAccessGranted: SharkeyEntity.NotificationType = 'sharedAccessGranted'
  export const SharedAccessRevoked: SharkeyEntity.NotificationType = 'sharedAccessRevoked'
  export const SharedAccessLogin: SharkeyEntity.NotificationType = 'sharedAccessLogin'
}

export default SharkeyNotificationType
