name: reviewdog

on:
  pull_request:

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.16.0'
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: |
        yarn install
    - uses: reviewdog/action-setup@v1
    - name: megalodon eslint
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        yarn workspace megalodon lint | reviewdog -f=eslint -reporter=github-pr-review -fail-on-error=true
    - name: example/typescript eslint
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        yarn workspace example lint | reviewdog -f=eslint -reporter=github-pr-review -fail-on-error=true
    - name: example/webpack eslint
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        yarn workspace webpack lint | reviewdog -f=eslint -reporter=github-pr-review -fail-on-error=true
    - name: example/vite eslint
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        yarn workspace vite lint | reviewdog -f=eslint -reporter=github-pr-review -fail-on-error=true
