name: reviewdog

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: |
        yarn install
    - uses: reviewdog/action-setup@v1
    - name: Run eslint
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        yarn workspace megalodon lint | reviewdog -f=eslint -reporter=github-pr-review -fail-on-error=true
